<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2fb60e62f228e1c3af6b57320475b12e
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dnsoftware\\Dncurrency\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dnsoftware\\Dncurrency\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2fb60e62f228e1c3af6b57320475b12e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2fb60e62f228e1c3af6b57320475b12e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
